In [1]:
import numpy as np
import pandas as pd

In [2]:
bestbooks = pd.read_csv('books_1.Best_Books_Ever.csv')
books = pd.read_csv('Books.csv', dtype=str, low_memory=False)
users = pd.read_csv('Users.csv')
ratings= pd.read_csv('Ratings.csv')

In [3]:
bestbooks = bestbooks.apply(lambda col: col.map(lambda x: x.replace("[", "").replace("]", "").replace("'", "") if isinstance(x, str) else x))

In [4]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [5]:
bestbooks.head()

,bookId,title,series,author,rating,description,language,isbn,genres,characters,...,firstPublishDate,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price
0,2767052-the-hunger-games,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"Young Adult, Fiction, Dystopia, Fantasy, Scien...","Katniss Everdeen, Peeta Mellark, Cato (Hunger ...",...,NaN,Locus Award Nominee for Best Young Adult Book ...,6376780,"3444695, 1921313, 745221, 171994, 93557",96.0,"District 12, Panem, Capitol, Panem, Panem (Uni...",https://i.gr-assets.com/images/S/compressed.ph...,2993816,30516,5.09
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"Fantasy, Young Adult, Fiction, Magic, Children...","Sirius Black, Draco Malfoy, Ron Weasley, Petun...",...,06/21/03,Bram Stoker Award for Works for Young Readers ...,2507623,"1593642, 637516, 222366, 39573, 14526",98.0,Hogwarts School of Witchcraft and Wizardry (Un...,https://i.gr-assets.com/images/S/compressed.ph...,2632233,26923,7.38
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"Classics, Fiction, Historical Fiction, School,...","Scout Finch, Atticus Finch, Jem Finch, Arthur ...",...,07/11/60,"Pulitzer Prize for Fiction (1961), Audie Award...",4501075,"2363896, 1333153, 573280, 149952, 80794",95.0,"Maycomb, Alabama (United States)",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,NaN
3,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,9999999999999,"Classics, Fiction, Romance, Historical Fiction...","Mr. Bennet, Mrs. Bennet, Jane Bennet, Elizabet...",...,01/28/13,,2998241,"1617567, 816659, 373311, 113934, 76770",94.0,"United Kingdom, Derbyshire, England (United Ki...",https://i.gr-assets.com/images/S/compressed.ph...,1983116,20452,NaN
4,41865.Twilight,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"Young Adult, Fantasy, Romance, Vampires, Ficti...","Edward Cullen, Jacob Black, Laurent, Renee, Be...",...,10/05/05,"Georgia Peach Book Award (2007), Buxtehuder Bu...",4964519,"1751460, 1113682, 1008686, 542017, 548674",78.0,"Forks, Washington (United States), Phoenix, Ar...",https://i.gr-assets.com/images/S/compressed.ph...,1459448,14874,2.1

In [6]:
#bestbooks.to_pickle('bestbooks.pkl')

In [7]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [8]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [9]:
print(bestbooks.shape)
print(books.shape)
print(users.shape)
print(ratings.shape)

(52478, 25)
(271360, 8)
(278858, 3)
(1149780, 3)

In [10]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [11]:
bestbooks.isnull().sum()

bookId                  0
title                   0
series              29008
author                  0
rating                  0
description          1338
language             3806
isbn                    0
genres                  0
characters              0
bookFormat           1473
edition             47523
pages                2347
publisher            3696
publishDate           880
firstPublishDate    21326
awards                  0
numRatings              0
ratingsByStars          0
likedPercent          622
setting                 0
coverImg              605
bbeScore                0
bbeVotes                0
price               14365
dtype: int64

In [12]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [13]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [14]:
bestbooks.duplicated().sum()

50

In [15]:
books.duplicated().sum()

0

In [16]:
users.duplicated().sum()

0

In [17]:
ratings.duplicated().sum()

0

In [18]:
bestbooks.fillna(bestbooks.mean(numeric_only=True), inplace=True)

In [19]:
numeric_cols = bestbooks.select_dtypes(include=['int64', 'float64']).columns
bestbooks[numeric_cols] = bestbooks[numeric_cols].fillna(bestbooks[numeric_cols].mean())

In [20]:
bestbooks.duplicated().sum()

50

In [21]:
books.columns = books.columns.str.lower()

In [22]:
books.head()

,isbn,book-title,book-author,year-of-publication,publisher,image-url-s,image-url-m,image-url-l
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [23]:
bestbooks = bestbooks.rename(columns={'title': 'book-title'})

In [24]:
books.merge(bestbooks,on='book-title')

,isbn_x,book-title,book-author,year-of-publication,publisher_x,image-url-s,image-url-m,image-url-l,bookId,series,...,firstPublishDate,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price
0,0440234743,The Testament,John Grisham,1999,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,5348.The_Testament,NaN,...,02/02/99,,106005,"30428, 39438, 28444, 6075, 1620",93.0,"United States of America, Corumba (Brazil), Mc...",https://i.gr-assets.com/images/S/compressed.ph...,2441,41,3.05
1,0345402871,Airframe,Michael Crichton,1997,Ballantine Books,http://images.amazon.com/images/P/0345402871.0...,http://images.amazon.com/images/P/0345402871.0...,http://images.amazon.com/images/P/0345402871.0...,7667.Airframe,NaN,...,11/27/96,,77459,"18024, 28146, 23548, 6229, 1512",90.0,"Los Angeles, California (United States)",https://i.gr-assets.com/images/S/compressed.ph...,360,4,2.76
2,0345417623,Timeline,MICHAEL CRICHTON,2000,Ballantine Books,http://images.amazon.com/images/P/0345417623.0...,http://images.amazon.com/images/P/0345417623.0...,http://images.amazon.com/images/P/0345417623.0...,7669.Timeline,NaN,...,11/16/99,,189871,"56175, 68939, 48337, 12912, 3508",91.0,France,https://i.gr-assets.com/images/S/compressed.ph...,6196,83,2.76
3,0375406328,Lying Awake,Mark Salzman,2000,Alfred A. Knopf,http://images.amazon.com/images/P/0375406328.0...,http://images.amazon.com/images/P/0375406328.0...,http://images.amazon.com/images/P/0375406328.0...,136228.Lying_Awake,NaN,...,11/06/00,,2761,"717, 1088, 755, 166, 35",93.0,,https://i.gr-assets.com/images/S/compressed.ph...,78,1,3.79
4,0446310786,To Kill a Mockingbird,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,...,07/11/60,"Pulitzer Prize for Fiction (1961), Audie Award...",4501075,"2363896, 1333153, 573280, 149952, 80794",95.0,"Maycomb, Alabama (United States)",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26247,0451520521,Babbitt,Sinclair Lewis,1982,Signet Book,http://images.amazon.com/images/P/0451520521.0...,http://images.amazon.com/images/P/0451520521.0...,http://images.amazon.com/images/P/0451520521.0...,169718.Babbitt,NaN,...,10/28/22,,21166,"4786, 7774, 6059, 1827, 720",88.0,,https://i.gr-assets.com/images/S/compressed.ph...,844,16,23.32
26248,1561569119,Robinson Crusoe,Daniel Defoe,1998,Kidsbooks,http://images.amazon.com/images/P/1561569119.0...,http://images.amazon.com/images/P/1561569119.0...,http://images.amazon.com/images/P/1561569119.0...,2932.Robinson_Crusoe,Robinson Crusoe #1,...,04/25/19,,247795,"60768, 84614, 71861, 22461, 8091",88.0,small island on mouth of Orinoco river,https://i.gr-assets.com/images/S/compressed.ph...,28064,420,NaN
26249,0451521390,Pathfinder,James Fenimore Cooper,1982,Signet Book,http://images.amazon.com/images/P/0451521390.0...,http://images.amazon.com/images/P/0451521390.0...,http://images.amazon.com/images/P/0451521390.0...,8100267-pathfinder,Pathfinder #1,...,09/01/10,Locus Award Nominee for Best Young Adult Book ...,21690,"7067, 9053, 4246, 986, 338",94.0,,https://i.gr-assets.com/images/S/compressed.ph...,193,2,1.86
26250,0441011799,Singularity Sky,Charles Stross,2004,Ace,http://images.amazon.com/images/P/0441011799.0...,http://images.amazon.com/images/P/0441011799.0...,http://images.amazon.com/images/P/0441011799.0...,81992.Singularity_Sky,Eschaton #1,...,08/05/03,Hugo Award Nominee for Best Novel (2004),13594,"3410, 5704, 3468, 813, 199",93.0,,https://i.gr-assets.com/images/S/compressed.ph...,148,2,3.96
26251,0395264707,Dreamsnake,Vonda N. McIntyre,1978,Houghton Mifflin,http://images.amazon.com/images/P/0395264707.0...,http://images.amazon.com/images/P/0395264707.0...,http://images.amazon.com/images/P/0395264707.0...,263021.Dreamsnake,NaN,...,03/30/78,"Hugo Award for Best Novel (1979), Nebula Award...",9027,"2746, 3292, 2182, 577, 230",91.0,,https://i.gr-assets.com/images/S/compressed.ph...,97,1,16.25

In [25]:
bestbooks.head()

,bookId,book-title,series,author,rating,description,language,isbn,genres,characters,...,firstPublishDate,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price
0,2767052-the-hunger-games,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"Young Adult, Fiction, Dystopia, Fantasy, Scien...","Katniss Everdeen, Peeta Mellark, Cato (Hunger ...",...,NaN,Locus Award Nominee for Best Young Adult Book ...,6376780,"3444695, 1921313, 745221, 171994, 93557",96.0,"District 12, Panem, Capitol, Panem, Panem (Uni...",https://i.gr-assets.com/images/S/compressed.ph...,2993816,30516,5.09
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"Fantasy, Young Adult, Fiction, Magic, Children...","Sirius Black, Draco Malfoy, Ron Weasley, Petun...",...,06/21/03,Bram Stoker Award for Works for Young Readers ...,2507623,"1593642, 637516, 222366, 39573, 14526",98.0,Hogwarts School of Witchcraft and Wizardry (Un...,https://i.gr-assets.com/images/S/compressed.ph...,2632233,26923,7.38
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"Classics, Fiction, Historical Fiction, School,...","Scout Finch, Atticus Finch, Jem Finch, Arthur ...",...,07/11/60,"Pulitzer Prize for Fiction (1961), Audie Award...",4501075,"2363896, 1333153, 573280, 149952, 80794",95.0,"Maycomb, Alabama (United States)",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,NaN
3,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,9999999999999,"Classics, Fiction, Romance, Historical Fiction...","Mr. Bennet, Mrs. Bennet, Jane Bennet, Elizabet...",...,01/28/13,,2998241,"1617567, 816659, 373311, 113934, 76770",94.0,"United Kingdom, Derbyshire, England (United Ki...",https://i.gr-assets.com/images/S/compressed.ph...,1983116,20452,NaN
4,41865.Twilight,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"Young Adult, Fantasy, Romance, Vampires, Ficti...","Edward Cullen, Jacob Black, Laurent, Renee, Be...",...,10/05/05,"Georgia Peach Book Award (2007), Buxtehuder Bu...",4964519,"1751460, 1113682, 1008686, 542017, 548674",78.0,"Forks, Washington (United States), Phoenix, Ar...",https://i.gr-assets.com/images/S/compressed.ph...,1459448,14874,2.1

In [26]:
books.head()

,isbn,book-title,book-author,year-of-publication,publisher,image-url-s,image-url-m,image-url-l
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [27]:
bestbooks = bestbooks.rename(columns={'title': 'book-title'})

In [28]:
books.merge(bestbooks,on='book-title')

,isbn_x,book-title,book-author,year-of-publication,publisher_x,image-url-s,image-url-m,image-url-l,bookId,series,...,firstPublishDate,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price
0,0440234743,The Testament,John Grisham,1999,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,5348.The_Testament,NaN,...,02/02/99,,106005,"30428, 39438, 28444, 6075, 1620",93.0,"United States of America, Corumba (Brazil), Mc...",https://i.gr-assets.com/images/S/compressed.ph...,2441,41,3.05
1,0345402871,Airframe,Michael Crichton,1997,Ballantine Books,http://images.amazon.com/images/P/0345402871.0...,http://images.amazon.com/images/P/0345402871.0...,http://images.amazon.com/images/P/0345402871.0...,7667.Airframe,NaN,...,11/27/96,,77459,"18024, 28146, 23548, 6229, 1512",90.0,"Los Angeles, California (United States)",https://i.gr-assets.com/images/S/compressed.ph...,360,4,2.76
2,0345417623,Timeline,MICHAEL CRICHTON,2000,Ballantine Books,http://images.amazon.com/images/P/0345417623.0...,http://images.amazon.com/images/P/0345417623.0...,http://images.amazon.com/images/P/0345417623.0...,7669.Timeline,NaN,...,11/16/99,,189871,"56175, 68939, 48337, 12912, 3508",91.0,France,https://i.gr-assets.com/images/S/compressed.ph...,6196,83,2.76
3,0375406328,Lying Awake,Mark Salzman,2000,Alfred A. Knopf,http://images.amazon.com/images/P/0375406328.0...,http://images.amazon.com/images/P/0375406328.0...,http://images.amazon.com/images/P/0375406328.0...,136228.Lying_Awake,NaN,...,11/06/00,,2761,"717, 1088, 755, 166, 35",93.0,,https://i.gr-assets.com/images/S/compressed.ph...,78,1,3.79
4,0446310786,To Kill a Mockingbird,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,...,07/11/60,"Pulitzer Prize for Fiction (1961), Audie Award...",4501075,"2363896, 1333153, 573280, 149952, 80794",95.0,"Maycomb, Alabama (United States)",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26247,0451520521,Babbitt,Sinclair Lewis,1982,Signet Book,http://images.amazon.com/images/P/0451520521.0...,http://images.amazon.com/images/P/0451520521.0...,http://images.amazon.com/images/P/0451520521.0...,169718.Babbitt,NaN,...,10/28/22,,21166,"4786, 7774, 6059, 1827, 720",88.0,,https://i.gr-assets.com/images/S/compressed.ph...,844,16,23.32
26248,1561569119,Robinson Crusoe,Daniel Defoe,1998,Kidsbooks,http://images.amazon.com/images/P/1561569119.0...,http://images.amazon.com/images/P/1561569119.0...,http://images.amazon.com/images/P/1561569119.0...,2932.Robinson_Crusoe,Robinson Crusoe #1,...,04/25/19,,247795,"60768, 84614, 71861, 22461, 8091",88.0,small island on mouth of Orinoco river,https://i.gr-assets.com/images/S/compressed.ph...,28064,420,NaN
26249,0451521390,Pathfinder,James Fenimore Cooper,1982,Signet Book,http://images.amazon.com/images/P/0451521390.0...,http://images.amazon.com/images/P/0451521390.0...,http://images.amazon.com/images/P/0451521390.0...,8100267-pathfinder,Pathfinder #1,...,09/01/10,Locus Award Nominee for Best Young Adult Book ...,21690,"7067, 9053, 4246, 986, 338",94.0,,https://i.gr-assets.com/images/S/compressed.ph...,193,2,1.86
26250,0441011799,Singularity Sky,Charles Stross,2004,Ace,http://images.amazon.com/images/P/0441011799.0...,http://images.amazon.com/images/P/0441011799.0...,http://images.amazon.com/images/P/0441011799.0...,81992.Singularity_Sky,Eschaton #1,...,08/05/03,Hugo Award Nominee for Best Novel (2004),13594,"3410, 5704, 3468, 813, 199",93.0,,https://i.gr-assets.com/images/S/compressed.ph...,148,2,3.96
26251,0395264707,Dreamsnake,Vonda N. McIntyre,1978,Houghton Mifflin,http://images.amazon.com/images/P/0395264707.0...,http://images.amazon.com/images/P/0395264707.0...,http://images.amazon.com/images/P/0395264707.0...,263021.Dreamsnake,NaN,...,03/30/78,"Hugo Award for Best Novel (1979), Nebula Award...",9027,"2746, 3292, 2182, 577, 230",91.0,,https://i.gr-assets.com/images/S/compressed.ph...,97,1,16.25

In [29]:
ratings.columns = ratings.columns.str.lower()

In [30]:
users.columns = users.columns.str.lower()

In [31]:
ratings_with_name = ratings.merge(books,on = 'isbn')

In [32]:
ratings_with_name

,user-id,isbn,book-rating,book-title,book-author,year-of-publication,publisher,image-url-s,image-url-m,image-url-l
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276704,0876044011,0,Edgar Cayce on the Akashic Records: The Book o...,Kevin J. Todeschi,1998,A.R.E. Press (Association of Research &amp; Enlig,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...
1031132,276704,1563526298,9,Get Clark Smart : The Ultimate Guide for the S...,Clark Howard,2000,Longstreet Press,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...
1031133,276706,0679447156,0,Eight Weeks to Optimum Health: A Proven Progra...,Andrew Weil,1997,Alfred A. Knopf,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...
1031134,276709,0515107662,10,The Sherbrooke Bride (Bride Trilogy (Paperback)),Catherine Coulter,1996,Jove Books,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...
1031135,276721,0590442449,10,Fourth Grade Rats,Jerry Spinelli,1996,Scholastic,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...

In [33]:
num_rating_df = ratings_with_name.groupby('book-title').count()['book-rating'].reset_index()
num_rating_df.rename(columns={'book-rating':'num_ratings'},inplace=True)
num_rating_df

                                               book-title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [34]:
ratings_with_name['book-rating'] = pd.to_numeric(ratings_with_name['book-rating'], errors='coerce')

In [35]:
ratings_with_name.dropna(subset=['book-rating'], inplace=True)

In [36]:
avg_rating_df = ratings_with_name.groupby('book-title')['book-rating'].mean().reset_index()
avg_rating_df.rename(columns={'book-rating': 'avg_rating'}, inplace=True)
avg_rating_df

                                               book-title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [37]:
popular_df = num_rating_df.merge(avg_rating_df,on = 'book-title')

In [38]:
popular_df

,book-title,num_ratings,avg_rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [39]:
popular_df = popular_df[popular_df['num_ratings']>=250].sort_values('avg_rating',ascending=False).head(50)

In [40]:
#popular_df = popular_df.merge(books, on='book-title').drop_duplicates('book-title')
popular_df = popular_df.merge(bestbooks, on='book-title').drop_duplicates('book-title')

In [41]:
popular_df.shape

(22, 27)

In [42]:
#popular_df = popular_df[['book-title', 'book-author', 'coverImg', 'num_ratings', 'avg_rating']]
print(popular_df.columns)

Index(['book-title', 'num_ratings', 'avg_rating', 'bookId', 'series', 'author',
       'rating', 'description', 'language', 'isbn', 'genres', 'characters',
       'bookFormat', 'edition', 'pages', 'publisher', 'publishDate',
       'firstPublishDate', 'awards', 'numRatings', 'ratingsByStars',
       'likedPercent', 'setting', 'coverImg', 'bbeScore', 'bbeVotes', 'price'],
      dtype='object')

In [43]:
popular_df

,book-title,num_ratings,avg_rating,bookId,series,author,rating,description,language,isbn,...,firstPublishDate,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price
0,To Kill a Mockingbird,510,4.700000,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,...,07/11/60,"Pulitzer Prize for Fiction (1961), Audie Award...",4501075,"2363896, 1333153, 573280, 149952, 80794",95.0,"Maycomb, Alabama (United States)",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,NaN
1,The Da Vinci Code,898,4.642539,968.The_Da_Vinci_Code,Robert Langdon #2,Dan Brown (Goodreads Author),3.86,ISBN 9780307277671 moved to this edition.While...,English,9999999999999,...,03/18/03,British Book Award for Book of the Year (2005)...,1933446,"645308, 667657, 399278, 142103, 79100",89.0,"Paris (France), London, England, France, Engla...",https://i.gr-assets.com/images/S/compressed.ph...,876633,9231,NaN
2,The Five People You Meet in Heaven,430,4.551163,3431.The_Five_People_You_Meet_in_Heaven,The Five People You Meet in Heaven #1,Mitch Albom (Goodreads Author),3.94,From the author of the phenomenal #1 New York ...,English,9781401308582,...,09/01/03,Lincoln Award Nominee (2008),578095,"210367, 189807, 125731, 37953, 14237",91.0,United States of America,https://i.gr-assets.com/images/S/compressed.ph...,125048,1441,3.57
3,The Catcher in the Rye,449,4.545657,5107.The_Catcher_in_the_Rye,NaN,J.D. Salinger,3.81,The hero-narrator of The Catcher in the Rye is...,English,9780316769174,...,07/16/51,Teen Read Award Nominee for Best All-Time-Fave...,2736523,"937208, 846027, 579292, 234980, 139016",86.0,"New York City, New York (United States), Agers...",https://i.gr-assets.com/images/S/compressed.ph...,603268,6533,2.6
4,1984,284,4.454225,40961427-1984,NaN,George Orwell,4.19,"Among the seminal texts of the 20th century, N...",English,B003JTHWKU,...,06/08/49,"Prometheus Hall of Fame Award (1984), Locus Aw...",3140442,"1474277, 1025880, 453693, 121946, 64646",94.0,"London, England, England, United Kingdom",https://i.gr-assets.com/images/S/compressed.ph...,324371,3544,NaN
5,Neverwhere,265,4.449057,14497.Neverwhere,"London Below, The World of Neverwhere #1",Neil Gaiman (Goodreads Author),4.17,Under the streets of London theres a place mos...,English,9780060557812,...,09/16/96,Mythopoeic Fantasy Award Nominee for Adult Lit...,429671,"183871, 159275, 66399, 14471, 5655",95.0,"London, England, England, United Kingdom",https://i.gr-assets.com/images/S/compressed.ph...,46087,565,4.66
6,The Secret Life of Bees,774,4.447028,37435.The_Secret_Life_of_Bees,NaN,Sue Monk Kidd (Goodreads Author),4.06,"Set in South Carolina in 1964, The Secret Life...",English,9780142001745,...,11/08/01,Orange Prize Nominee for Fiction Longlist (200...,1116565,"428034, 410900, 208952, 49676, 19003",94.0,"United States of America, South Carolina (Unit...",https://i.gr-assets.com/images/S/compressed.ph...,179134,2051,3.5
7,Into the Wild,252,4.273810,1845.Into_the_Wild,NaN,Jon Krakauer (Goodreads Author),3.99,Librarians Note: An alternate cover edition ca...,English,9780385486804,...,10/28/96,Washington State Book Award (1997),878855,"318776, 322679, 169307, 44022, 24071",92.0,"Mexico, Virginia (United States), The Slabs, M...",https://i.gr-assets.com/images/S/compressed.ph...,46018,583,3.75
10,Fahrenheit 451,409,4.264059,13079982-fahrenheit-451,NaN,Ray Bradbury,3.99,"Guy Montag is a fireman. In his world, where t...",English,B0064CPN7I,...,10/19/53,"Prometheus Hall of Fame Award (1984), Geffen A...",1680139,"612098, 604888, 331815, 91160, 40178",92.0,,https://i.gr-assets.com/images/S/compressed.ph...,793757,8537,NaN
11,Girl with a Pearl Earring,526,4.218631,2865.Girl_with_a_Pearl_Earring,NaN,Tracy Chevalier (Goodreads Author),3.89,"With precisely 35 canvases to his credit, the ...",English,9780452287020,...,10/28/99,Orange Prize Nominee for Fiction Longlist (200...,626689,"194523, 235382, 146900, 33893, 15991",92.0,"Delft (Netherlands), Netherlands",https://i.gr-assets.com/images/S/compressed.ph...,57743,752,2.86
12,Outlander,283,4.173145,10964.Outlander,Outlander #1,Diana Gabaldon (Goodreads Author),4.23,"The year is 1945. Claire Randall, a former com...",English,9780440242949,...,06/01/91,RITA Award by Romance Writers of America for B...,824014,"449748, 207613, 100271, 37903, 28479",92.0,"Lallybroch, Scotland (United Kingdom), Scottis...",https://i.gr-assets.com/images/S/compressed.ph...,342024,3661,5.98
13,Seabiscuit: An American Legend,275,4.098182,110737.Seabiscuit,NaN,Laura Hillenbrand,4.22,Theres an alternate cover edition hereSeabiscu...,English,9780345465085,...,06/30/99,Book Sense Book of the Year Award for Adult No...,144419,"66572, 50847, 20985, 4168, 1847",96.0,United States of America,https://i.gr-assets.com/images/S/compressed.ph...,12822,190,3.19
14,Life of Pi,664,4.088855,4214.Life_of_Pi,NaN,Yann Martel,3.91,Life of Pi is a fantasy adventure novel by Yan...,English,9780770430078,...,09/11/01,"Booker Prize (2002), Bollinger Everyman Wodeho...",1339076,"464957, 475177, 264628, 87693, 46621",90.0,"Pacific Ocean, Pondicherry (India), Toronto, O...",https://i.gr-assets.com/images/S/compressed.ph...,490471,5307,2.86
15,The Bean Trees,389,4.087404,30868.The_Bean_Trees,Greer Family #1,Barbara Kingsolver,3.97,"Clear-eyed and spirited, Taylor Greer grew up ...",English,9780812474947,...,12/01/88,,135045,"41907, 56465, 29503, 5584, 1586",95.0,"Tucson, Arizona (United States)",https://i.gr-assets.com/images/S/compressed.ph...,14620,215,4.59
16,Good in Bed,490,4.055102,14748.Good_in_Bed,Cannie Shapiro #1,Jennifer Weiner (Goodreads Author),3.73,"Weiners witty, original, fast-moving debut fea...",English,9780743418171,...,10/28/01,,279594,"79129, 93424, 71805, 22034, 13202",87.0,"Philadelphia, Pennsylvania (United States)",https://i.gr-assets.com/images/S/compressed.ph...,2295,36,3.09
17,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383,1097.Fast_Food_Nation,NaN,Eric Schlosser,3.75,Fast food has hastened the malling of our land...,English,9780060838584,...,01/17/01,Puddly Award for Nonfiction (2003),197560,"51010, 74615, 50794, 12928, 8213",89.0,"Colorado Springs, Colorado (United States)",https://i.gr-assets.com/images/S/compressed.ph...,3294,55,3.09
18,American Gods,302,4.006623,30165203-american-gods,American Gods #1,Neil Gaiman (Goodreads Author),4.11,"Days before his release from prison, Shadows w...",English,9999999999999,...,06/19/01,"Bram Stoker Award for Best Novel (2001), Hugo ...",758439,"324019, 259232, 122365, 37228, 15595",93.0,"United States of America, Chicago, Illinois (U...",https://i.gr-assets.com/images/S/compressed.ph...,119803,1357,NaN
19,Skipping Christmas,322,4.006211,5357.Skipping_Christmas,NaN,John Grisham (Goodreads Author),3.50,Imagine a year without Christmas. No crowded s...,English,9780099481683,...,11/06/01,,56863,"11325, 17038, 19314, 7037, 2149",84.0,United States of America,https://i.gr-assets.com/images/S/compressed.ph...,424,6,1.79
20,The Color Purple,314,3.964968,52892857-the-color-purple,The Color Purple Collection #1,Alice Walker,4.22,Winner of the Pulitzer Prize and the National ...,English,9780143135692,...,10/28/82,"Pulitzer Prize for Fiction (1983), National Bo...",521200,"244193, 179134, 74068, 16614, 7191",95.0,Georgia (United States),https://i.gr-assets.com/images/S/compressed.ph...,319385,3631,13.75
21,About a Boy,262,3.900763,4271.About_a_Boy,NaN,Nick Hornby,3.79,How cool was Will Freeman?Too cool! At thirty-...,English,9780140285673,...,05/11/98,,125733,"27091, 55180, 35478, 6438, 1546",94.0,,https://i.gr-assets.com/images/S/compressed.ph...,3764,59,2.93
22,Lord of the Flies,259,3.818533,7624.Lord_of_the_Flies,NaN,William Golding,3.69,"At the dawn of the next world war, a plane cra...",English,9780140283334,...,09/17/54,,2263259,"617568, 763438, 555614, 205804, 120835",86.0,,https://i.gr-assets.com/images/S/compressed.ph...,773560,8230,1.89
23,A Prayer for Owen Meany,413,3.796610,4473.A_Prayer_for_Owen_Meany,NaN,John Irving (Goodreads Author),4.23,"Eleven-year-old Owen Meany, playing in a Littl...",English,9780552135399,...,03/28/89,,285954,"143125, 87919, 38471, 11140, 5299",94.0,"Gravesend, New Hampshire (United States), Toro...",https://i.gr-assets.com/images/S/compressed.ph...,207241,2280,2.86

In [44]:
popular_df.to_pickle('popular1.pkl')

In [45]:
##Collaborative filtering based

In [46]:
ratings_with_name.groupby('user-id').count()['book-rating']

user-id
2          1
8         17
9          3
10         1
12         1
          ..
278846     1
278849     4
278851    23
278852     1
278854     8
Name: book-rating, Length: 92106, dtype: int64

In [47]:
x = ratings_with_name.groupby('user-id').count()['book-rating'] > 200

In [48]:
goodusers = x[x].index

In [49]:
ratings_with_name[ratings_with_name['user-id'].isin(goodusers)]

,user-id,isbn,book-rating,book-title,book-author,year-of-publication,publisher,image-url-s,image-url-m,image-url-l
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1151,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...
1152,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...
1153,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...
1154,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...
...,...,...,...,...,...,...,...,...,...,...
1029357,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1029358,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...
1029359,275970,3829021860,0,The Penis Book,Joseph Cohen,1999,Konemann,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...
1029360,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995,Kodansha International (JPN),http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...
1029361,275970,9626340762,8,Northanger Abbey (Classic Literature with Clas...,Jane Austen,1996,Naxos Audiobooks Ltd.,http://images.amazon.com/images/P/9626340762.0...,http://images.amazon.com/images/P/9626340762.0...,http://images.amazon.com/images/P/9626340762.0...

In [50]:
filtered_rating  =  ratings_with_name[ratings_with_name['user-id'].isin(goodusers)]

In [51]:
y=filtered_rating.groupby('book-title').count()['book-rating']>=50
famous_books = y[y].index

In [52]:
final_ratings = filtered_rating[filtered_rating['book-title'].isin(famous_books)]

In [53]:
pt = final_ratings.pivot_table(index= 'book-title',columns='user-id',values='book-rating')

In [54]:
pt.fillna(0,inplace=True)

In [55]:
pt

user-id,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
book-title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [56]:
from sklearn.metrics.pairwise import cosine_similarity

In [57]:
from sklearn.metrics.pairwise import cosine_similarity

In [58]:
similarity_scores = cosine_similarity(pt)

In [59]:
pt

user-id,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
book-title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [60]:
similarity_scores.shape

(706, 706)

In [61]:
def recommend(book_name):
    #index fetch
    return suggesstions

In [62]:
import numpy as np

# Convert bestbooks DataFrame into a set for faster lookup
bestbooks_set = set(bestbooks['book-title'].str.strip().str.lower())  # Normalize titles

def recommend(book_name):
    # Normalize input book title to match bestbooks format
    book_name_normalized = book_name.strip().lower()

    # Convert pt.index to a list for string operations
    pt_index_list = [title.strip().lower() for title in pt.index.tolist()]

    # Check if the book is in the dataset
    if book_name_normalized not in pt_index_list:
        print("\nBook not found in dataset.")
        return

    # Fetch index of the given book
    index = np.where(np.array(pt_index_list) == book_name_normalized)[0].item()

    # Sort similarity scores in descending order
    similar_items = sorted(
        list(enumerate(similarity_scores[index])),
        key=lambda x: x[1],
        reverse=True
    )

    # Filter out books with zero similarity and ensure they exist in bestbooks
    filtered_books = [
        pt.index[i[0]] for i in similar_items 
        if i[1] > 0 and pt.index[i[0]].strip().lower() in bestbooks_set
    ][1:6]  # Skip first item (it’s the input book itself)

    if filtered_books:
        print("\nRecommended books for:", book_name)
        for book in filtered_books:
            print(book)
    else:
        print("\nNo similar books found in bestbooks for:", book_name)

In [63]:
recommend('1984')

Recommended books for: 1984
Animal Farm
Brave New World
Fahrenheit 451
The Catcher in the Rye
Naked

In [64]:
similarity_scores[0]

array([1.        , 0.10255025, 0.01220856, 0.        , 0.05367224,
       0.02774901, 0.08216491, 0.13732869, 0.03261686, 0.03667591,
       0.02322418, 0.06766487, 0.02083978, 0.09673735, 0.13388865,
       0.08303112, 0.11153543, 0.05100411, 0.02517784, 0.11706383,
       0.        , 0.14333793, 0.07847534, 0.06150451, 0.08723968,
       0.        , 0.07009814, 0.13658681, 0.07600328, 0.12167134,
       0.00768046, 0.01473221, 0.        , 0.07965814, 0.04522617,
       0.01556271, 0.09495938, 0.0182307 , 0.02610465, 0.07984012,
       0.11679969, 0.0569124 , 0.08354155, 0.08471898, 0.08785938,
       0.05491435, 0.0548505 , 0.27026514, 0.09779123, 0.06016046,
       0.08958835, 0.06748675, 0.        , 0.04468098, 0.01920872,
       0.        , 0.05629067, 0.00557964, 0.07877059, 0.05219479,
       0.18908177, 0.        , 0.01240656, 0.02984572, 0.04279502,
       0.12680125, 0.16566735, 0.        , 0.13357242, 0.06615478,
       0.        , 0.        , 0.        , 0.10968075, 0.02806606,
       0.04521795, 0.02613277, 0.06876131, 0.01331627, 0.10519138,
       0.03349457, 0.01363458, 0.23669374, 0.        , 0.10397941,
       0.06167753, 0.14176273, 0.11661083, 0.08331012, 0.00850895,
       0.06715433, 0.        , 0.15850821, 0.0328052 , 0.01068915,
       0.02579782, 0.02114859, 0.02687779, 0.02175821, 0.        ,
       0.01601663, 0.12114266, 0.04768603, 0.05819184, 0.06510722,
       0.        , 0.0476705 , 0.05273165, 0.0281001 , 0.06524573,
       0.02116345, 0.02097868, 0.07422249, 0.01752778, 0.03734567,
       0.        , 0.01579666, 0.11039448, 0.16527277, 0.15514319,
       0.06237454, 0.08139489, 0.05655414, 0.07458203, 0.03771888,
       0.0593633 , 0.02955369, 0.03355603, 0.04734093, 0.01006643,
       0.01671982, 0.07258935, 0.        , 0.        , 0.        ,
       0.02428501, 0.03067819, 0.0997498 , 0.        , 0.01690152,
       0.02410862, 0.0281084 , 0.        , 0.        , 0.01812877,
       0.02880827, 0.        , 0.05995157, 0.02127671, 0.1034119 ,
       0.02766748, 0.10684795, 0.09898722, 0.14145186, 0.05007429,
       0.09428289, 0.01411249, 0.        , 0.07835976, 0.00882242,
       0.04515898, 0.        , 0.01281412, 0.04003334, 0.07477661,
       0.01217906, 0.01887393, 0.02667484, 0.01432864, 0.14702847,
       0.06087282, 0.02578321, 0.02741876, 0.        , 0.14909595,
       0.05606788, 0.        , 0.03199916, 0.03643817, 0.        ,
       0.01962921, 0.22222254, 0.01515845, 0.09673268, 0.02190023,
       0.02013549, 0.05400331, 0.07262017, 0.01111637, 0.03649872,
       0.05994664, 0.        , 0.14691167, 0.02086005, 0.10359635,
       0.09794375, 0.06609997, 0.12871083, 0.08992739, 0.01147457,
       0.02460165, 0.        , 0.18049207, 0.05141892, 0.0477174 ,
       0.10849696, 0.13278139, 0.05915288, 0.05372984, 0.034785  ,
       0.        , 0.09203039, 0.06388401, 0.04773328, 0.15570975,
       0.08420691, 0.12338217, 0.0878469 , 0.08205945, 0.12177532,
       0.02433703, 0.00272862, 0.        , 0.        , 0.03671505,
       0.15280984, 0.0370943 , 0.07458136, 0.09746697, 0.05416091,
       0.10266993, 0.07574414, 0.06426526, 0.0360174 , 0.01559752,
       0.02033559, 0.02463593, 0.        , 0.03349154, 0.02135369,
       0.0190337 , 0.06806265, 0.02032116, 0.11784706, 0.07839488,
       0.08422558, 0.        , 0.02040796, 0.        , 0.04698246,
       0.08294513, 0.13974514, 0.01234525, 0.13510608, 0.07423489,
       0.11841889, 0.04930091, 0.01621668, 0.02633023, 0.04815972,
       0.01959826, 0.10174253, 0.13257638, 0.        , 0.0551027 ,
       0.0186115 , 0.        , 0.04504598, 0.03482459, 0.16503292,
       0.08466191, 0.06795353, 0.02987653, 0.        , 0.        ,
       0.08781993, 0.07885279, 0.04799058, 0.01467964, 0.02123837,
       0.04549923, 0.08673969, 0.00885998, 0.02880637, 0.02022145,
       0.02414122, 0.12548312, 0.        , 0.02482518, 0.06520606,
       0.        , 0.0606983 , 0.01177824, 0.13974105, 0.01978844,
       0.01260824, 0.08608601, 0.04433883, 0.02943085, 0.02242496,
       0.06541868, 0.07866868, 0.14281399, 0.11979305, 0.01858409,
       0.13445377, 0.04809338, 0.09790644, 0.        , 0.17415731,
       0.07437756, 0.        , 0.12389065, 0.01042391, 0.02580849,
       0.        , 0.0895139 , 0.04005551, 0.19182231, 0.02267512,
       0.01730347, 0.03054044, 0.07008822, 0.10084626, 0.10467615,
       0.01683462, 0.12468283, 0.10266459, 0.03549836, 0.02667484,
       0.07652765, 0.08474056, 0.01831977, 0.02177482, 0.15293362,
       0.        , 0.        , 0.01063251, 0.02153089, 0.02946443,
       0.        , 0.02076783, 0.01194825, 0.00953675, 0.2067554 ,
       0.01554292, 0.0390266 , 0.06681046, 0.09014973, 0.05914735,
       0.06206857, 0.        , 0.02005959, 0.07843566, 0.16337845,
       0.07161075, 0.        , 0.14595258, 0.07561631, 0.02939738,
       0.04779629, 0.01807238, 0.11362722, 0.09791273, 0.07999693,
       0.08912337, 0.10941777, 0.        , 0.02115842, 0.0600393 ,
       0.01797154, 0.05755408, 0.02166863, 0.09754449, 0.13107652,
       0.        , 0.06829904, 0.09132922, 0.        , 0.02781406,
       0.01533368, 0.06113179, 0.01757286, 0.02471294, 0.0180158 ,
       0.11789806, 0.06468143, 0.13904191, 0.        , 0.06671644,
       0.        , 0.        , 0.05762086, 0.02266096, 0.00844876,
       0.02297481, 0.07136276, 0.15305514, 0.06039874, 0.        ,
       0.08996912, 0.01545947, 0.10135299, 0.        , 0.01676344,
       0.        , 0.0502188 , 0.16041182, 0.        , 0.13439733,
       0.12508514, 0.02329035, 0.0198727 , 0.01105674, 0.02548034,
       0.00896044, 0.08246122, 0.01902896, 0.07025003, 0.0216367 ,
       0.12822982, 0.09998772, 0.08642895, 0.06355197, 0.02883024,
       0.04335826, 0.0470659 , 0.05223733, 0.        , 0.08982751,
       0.00875634, 0.09923542, 0.10228551, 0.        , 0.12307492,
       0.01758929, 0.02028125, 0.1033827 , 0.13028171, 0.08988894,
       0.09005001, 0.05332049, 0.08033436, 0.04597795, 0.06139888,
       0.02300709, 0.02304904, 0.06523041, 0.01915363, 0.        ,
       0.04542766, 0.        , 0.        , 0.05261954, 0.01317088,
       0.        , 0.        , 0.0485931 , 0.0734819 , 0.10354481,
       0.01718807, 0.09919937, 0.08091989, 0.00358835, 0.04757132,
       0.11122765, 0.05143481, 0.0566614 , 0.        , 0.06087719,
       0.10800615, 0.        , 0.07554686, 0.        , 0.13644384,
       0.04796763, 0.16104067, 0.        , 0.01759864, 0.05438295,
       0.        , 0.08100801, 0.13090711, 0.00581844, 0.07150547,
       0.05428487, 0.06143184, 0.05161653, 0.1951182 , 0.1149488 ,
       0.06513047, 0.06401961, 0.        , 0.        , 0.10853662,
       0.11400426, 0.0463925 , 0.01825277, 0.        , 0.01195201,
       0.21057744, 0.05809707, 0.04349156, 0.02646256, 0.07276403,
       0.05264857, 0.07242165, 0.06790898, 0.01626564, 0.02431809,
       0.02093565, 0.13617057, 0.11784149, 0.08588206, 0.09284352,
       0.11277297, 0.06868983, 0.08200947, 0.13369059, 0.        ,
       0.19972625, 0.02286207, 0.0806288 , 0.        , 0.05756015,
       0.06738056, 0.        , 0.19656288, 0.06306426, 0.03499381,
       0.06123119, 0.09596456, 0.02180168, 0.02317515, 0.06476149,
       0.07052241, 0.08280452, 0.1700872 , 0.07213921, 0.01172201,
       0.08541218, 0.17990898, 0.08007284, 0.01739625, 0.16728777,
       0.26396194, 0.1840891 , 0.05600273, 0.04133586, 0.06911015,
       0.14456847, 0.22626397, 0.19208896, 0.0239334 , 0.20025064,
       0.01507653, 0.05144282, 0.1233368 , 0.1420166 , 0.02472079,
       0.08563805, 0.02363426, 0.12794024, 0.01083153, 0.07352436,
       0.09532519, 0.03421895, 0.07194212, 0.02297079, 0.15344079,
       0.08856302, 0.        , 0.        , 0.01878656, 0.09772942,
       0.04404359, 0.15211972, 0.0152225 , 0.10307399, 0.05715789,
       0.04600056, 0.06303899, 0.06572303, 0.14421331, 0.08272478,
       0.        , 0.04203701, 0.02276077, 0.17381829, 0.01909967,
       0.16000268, 0.14681486, 0.        , 0.05940546, 0.07725115,
       0.07464763, 0.06546696, 0.07021577, 0.18921368, 0.02494136,
       0.01705027, 0.05437622, 0.04932819, 0.        , 0.11445399,
       0.08001595, 0.12858515, 0.02306658, 0.06129105, 0.02090769,
       0.04550867, 0.1026659 , 0.10725982, 0.0260534 , 0.00173709,
       0.0987294 , 0.08077482, 0.02159226, 0.01614275, 0.0208464 ,
       0.09797466, 0.01906731, 0.18571699, 0.05344577, 0.18925314,
       0.05894189, 0.01488161, 0.1202478 , 0.09840359, 0.01048126,
       0.10596224, 0.07617195, 0.0805439 , 0.        , 0.23299389,
       0.01073642, 0.13573542, 0.04578552, 0.14440017, 0.        ,
       0.12522954, 0.0645501 , 0.02817522, 0.14445559, 0.01721045,
       0.09508161, 0.0517902 , 0.18410818, 0.08704224, 0.10990764,
       0.10850377, 0.03954865, 0.0383631 , 0.02463491, 0.07845405,
       0.03455548, 0.03007681, 0.02484076, 0.04223674, 0.14444517,
       0.12340234, 0.01510201, 0.0284437 , 0.02132016, 0.07391778,
       0.08904276, 0.15893871, 0.06947574, 0.01060787, 0.        ,
       0.09993169, 0.05711356, 0.09488374, 0.00948943, 0.13365876,
       0.05794064, 0.        , 0.06721284, 0.02066998, 0.        ,
       0.01839428, 0.        , 0.12655364, 0.08418288, 0.09095705,
       0.00730589, 0.08143881, 0.        , 0.04218803, 0.08392849,
       0.07785801, 0.        , 0.07151794, 0.02407593, 0.01635126,
       0.03734567, 0.05237227, 0.01140169, 0.00968725, 0.12530648,
       0.00909905, 0.05864096, 0.01769644, 0.12110367, 0.07347567,
       0.04316046])

In [65]:
import pickle

with open('similarity_scores1.pkl', 'wb') as f:
    pickle.dump(similarity_scores, f)

In [66]:
sorted(list(enumerate(similarity_scores[0])),key = lambda x:x[1],reverse=True)[1:6]

[(47, 0.2702651417103732),
 (545, 0.2639619371123497),
 (82, 0.23669374347400993),
 (634, 0.23299389358170394),
 (551, 0.2262639743141286)]

In [67]:
recommend('Message in a Bottle')

Recommended books for: Message in a Bottle
Nights in Rodanthe
The Mulberry Tree
A Walk to Remember
Sanctuary
Midnight Bayou

In [68]:
#mood based filtering

In [69]:
print(bestbooks.columns)

Index(['bookId', 'book-title', 'series', 'author', 'rating', 'description',
       'language', 'isbn', 'genres', 'characters', 'bookFormat', 'edition',
       'pages', 'publisher', 'publishDate', 'firstPublishDate', 'awards',
       'numRatings', 'ratingsByStars', 'likedPercent', 'setting', 'coverImg',
       'bbeScore', 'bbeVotes', 'price'],
      dtype='object')

In [70]:
moodbooks = books.merge(bestbooks,on='book-title')

In [71]:
print(moodbooks['genres'].unique())

['Fiction, Thriller, Mystery, Legal Thriller, Suspense, Crime, Mystery Thriller, Law, Adult Fiction, Novels'
 'Fiction, Thriller, Mystery, Science Fiction, Suspense, Mystery Thriller, Adventure, Novels, Action, Aviation'
 'Science Fiction, Fiction, Thriller, Time Travel, Historical Fiction, Fantasy, Adventure, Historical, Science Fiction Fantasy, Suspense'
 ...
 'Science Fiction, Fantasy, Fiction, Alternate History, Steampunk, Mystery, Adult, Science Fiction Fantasy, Speculative Fiction, Space'
 'Fantasy, Fiction, Mythology, Classics, Epic Fantasy, High Fantasy, Sword and Sorcery, Adventure, Science Fiction Fantasy, Science Fiction'
 'Fantasy, Science Fiction, Young Adult, Fiction, Time Travel, Adventure, Science Fiction Fantasy, Dystopia, Audiobook, Teen']

In [72]:

mood_to_genres = {
    'happy': ['Comedy', 'Humor', 'Adventure', 'Romance'],
    'sad': ['Tragedy', 'Drama', 'Historical Fiction'],
    'exciting': ['Thriller', 'Mystery', 'Crime', 'Action', 'Suspense', 'Fantasy', 'Science Fiction'],
    'relaxing': ['Contemporary', 'Poetry', 'Self-Help', 'Historical'],
    'thoughtful': ['Nonfiction', 'Politics', 'Reference', 'Literature', 'Philosophy'],
    'curious': ['Fantasy', 'Science Fiction', 'Alternate History', 'Mythology', 'Speculative Fiction']
}

In [73]:
def map_genres_to_mood(genre_list):
    for genre in genre_list:
        for mood, genres in mood_to_genres.items():
            if genre in genres:
                return mood
    return 'other'

In [74]:
import ast
#moodbooks['genre_list'] = moodbooks['genres'].apply(lambda x: ast.literal_eval(x))
moodbooks['genre_list'] = moodbooks['genres'].apply(lambda x: x.split(", ") if isinstance(x, str) else [])

In [75]:

moodbooks['mood'] = moodbooks['genre_list'].apply(map_genres_to_mood)

In [76]:
happy_books = moodbooks[moodbooks['mood'] == 'happy']
happy_books = happy_books.drop_duplicates(subset='book-title')
happy_books.head()

,isbn_x,book-title,book-author,year-of-publication,publisher_x,image-url-s,image-url-m,image-url-l,bookId,series,...,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price,genre_list,mood
7,055321215X,Pride and Prejudice,Jane Austen,1983,Bantam,http://images.amazon.com/images/P/055321215X.0...,http://images.amazon.com/images/P/055321215X.0...,http://images.amazon.com/images/P/055321215X.0...,1885.Pride_and_Prejudice,NaN,...,2998241,"1617567, 816659, 373311, 113934, 76770",94.0,"United Kingdom, Derbyshire, England (United Ki...",https://i.gr-assets.com/images/S/compressed.ph...,1983116,20452,NaN,"[Classics, Fiction, Romance, Historical Fictio...",happy
16,0451625889,The Prince,Niccolo Machiavelli,1952,Signet Book,http://images.amazon.com/images/P/0451625889.0...,http://images.amazon.com/images/P/0451625889.0...,http://images.amazon.com/images/P/0451625889.0...,15820748-the-prince,The Selection #0.5,...,67132,"23946, 21267, 16612, 4252, 1055",92.0,,https://i.gr-assets.com/images/S/compressed.ph...,770,9,NaN,"[Young Adult, Romance, Dystopia, Novella, Fant...",happy
24,0446608653,The Alibi,Sandra Brown,2000,Warner Books,http://images.amazon.com/images/P/0446608653.0...,http://images.amazon.com/images/P/0446608653.0...,http://images.amazon.com/images/P/0446608653.0...,30347.The_Alibi,NaN,...,23510,"8278, 9148, 5001, 851, 232",95.0,"Charleston, South Carolina (United States)",https://i.gr-assets.com/images/S/compressed.ph...,91,1,3.28,"[Romance, Mystery, Romantic Suspense, Suspense...",happy
26,0446612545,The Beach House,James Patterson,2003,Warner Books,http://images.amazon.com/images/P/0446612545.0...,http://images.amazon.com/images/P/0446612545.0...,http://images.amazon.com/images/P/0446612545.0...,7512.The_Beach_House,Beach House #1,...,23125,"10042, 8882, 3516, 531, 154",97.0,,https://i.gr-assets.com/images/S/compressed.ph...,156,2,3.14,"[Fiction, Chick Lit, Romance, Southern, Contem...",happy
30,0812575954,The Deal,Joe Hutsko,2000,Tor Books (Mm),http://images.amazon.com/images/P/0812575954.0...,http://images.amazon.com/images/P/0812575954.0...,http://images.amazon.com/images/P/0812575954.0...,24920901-the-deal,Off-Campus #1,...,139648,"70640, 45871, 16828, 3808, 2501",95.0,,https://i.gr-assets.com/images/S/compressed.ph...,1635,20,NaN,"[Romance, New Adult, Contemporary, Sports, Col...",happy

In [77]:
sad_books = moodbooks[moodbooks['mood'] == 'sad']
sad_books = sad_books.drop_duplicates(subset='book-title')
sad_books.head()

,isbn_x,book-title,book-author,year-of-publication,publisher_x,image-url-s,image-url-m,image-url-l,bookId,series,...,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price,genre_list,mood
4,0446310786,To Kill a Mockingbird,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,...,4501075,"2363896, 1333153, 573280, 149952, 80794",95.0,"Maycomb, Alabama (United States)",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,NaN,"[Classics, Fiction, Historical Fiction, School...",sad
11,0380715899,A Soldier of the Great War,Mark Helprin,1992,Avon Books,http://images.amazon.com/images/P/0380715899.0...,http://images.amazon.com/images/P/0380715899.0...,http://images.amazon.com/images/P/0380715899.0...,87985.A_Soldier_of_the_Great_War,NaN,...,6586,"3688, 1887, 698, 227, 86",95.0,,https://i.gr-assets.com/images/S/compressed.ph...,1179,14,3.99,"[Fiction, Historical Fiction, War, Italy, Worl...",sad
13,0804106304,The Joy Luck Club,Amy Tan,1994,Prentice Hall (K-12),http://images.amazon.com/images/P/0804106304.0...,http://images.amazon.com/images/P/0804106304.0...,http://images.amazon.com/images/P/0804106304.0...,7763.The_Joy_Luck_Club,NaN,...,597870,"197959, 224003, 128294, 32176, 15438",92.0,"San Francisco, California (United States), China",https://i.gr-assets.com/images/S/compressed.ph...,82631,1037,4.74,"[Fiction, Historical Fiction, Classics, China,...",sad
21,0451166892,The Pillars of the Earth,Ken Follett,1996,Signet Book,http://images.amazon.com/images/P/0451166892.0...,http://images.amazon.com/images/P/0451166892.0...,http://images.amazon.com/images/P/0451166892.0...,5043.The_Pillars_of_the_Earth,Kingsbridge #1,...,648793,"354788, 189091, 71541, 21183, 12190",95.0,England,https://i.gr-assets.com/images/S/compressed.ph...,392260,4221,NaN,"[Historical Fiction, Fiction, Historical, Fant...",sad
38,0380778556,Rebecca,Daphne Du Maurier,1994,Avon,http://images.amazon.com/images/P/0380778556.0...,http://images.amazon.com/images/P/0380778556.0...,http://images.amazon.com/images/P/0380778556.0...,959330.Rebecca,NaN,...,52,"7, 20, 18, 6, 1",87.0,,https://i.gr-assets.com/images/S/compressed.ph...,99,1,3.48,"[Childrens, Young Adult, Historical Fiction]",sad

In [78]:
exciting_books = moodbooks[moodbooks['mood'] == 'exciting']
exciting_books = exciting_books.drop_duplicates(subset='book-title')
exciting_books.head()

,isbn_x,book-title,book-author,year-of-publication,publisher_x,image-url-s,image-url-m,image-url-l,bookId,series,...,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price,genre_list,mood
0,0440234743,The Testament,John Grisham,1999,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,5348.The_Testament,NaN,...,106005,"30428, 39438, 28444, 6075, 1620",93.0,"United States of America, Corumba (Brazil), Mc...",https://i.gr-assets.com/images/S/compressed.ph...,2441,41,3.05,"[Fiction, Thriller, Mystery, Legal Thriller, S...",exciting
1,0345402871,Airframe,Michael Crichton,1997,Ballantine Books,http://images.amazon.com/images/P/0345402871.0...,http://images.amazon.com/images/P/0345402871.0...,http://images.amazon.com/images/P/0345402871.0...,7667.Airframe,NaN,...,77459,"18024, 28146, 23548, 6229, 1512",90.0,"Los Angeles, California (United States)",https://i.gr-assets.com/images/S/compressed.ph...,360,4,2.76,"[Fiction, Thriller, Mystery, Science Fiction, ...",exciting
2,0345417623,Timeline,MICHAEL CRICHTON,2000,Ballantine Books,http://images.amazon.com/images/P/0345417623.0...,http://images.amazon.com/images/P/0345417623.0...,http://images.amazon.com/images/P/0345417623.0...,7669.Timeline,NaN,...,189871,"56175, 68939, 48337, 12912, 3508",91.0,France,https://i.gr-assets.com/images/S/compressed.ph...,6196,83,2.76,"[Science Fiction, Fiction, Thriller, Time Trav...",exciting
8,0553582747,From the Corner of His Eye,Dean Koontz,2001,Bantam Books,http://images.amazon.com/images/P/0553582747.0...,http://images.amazon.com/images/P/0553582747.0...,http://images.amazon.com/images/P/0553582747.0...,65948.From_the_Corner_of_His_Eye,NaN,...,29134,"11192, 9947, 6176, 1385, 434",94.0,,https://i.gr-assets.com/images/S/compressed.ph...,505,6,3.80,"[Horror, Fiction, Thriller, Suspense, Mystery,...",exciting
9,042518630X,Purity in Death,J.D. Robb,2002,Berkley Publishing Group,http://images.amazon.com/images/P/042518630X.0...,http://images.amazon.com/images/P/042518630X.0...,http://images.amazon.com/images/P/042518630X.0...,238137.Purity_in_Death,In Death #15,...,24713,"12359, 8967, 3112, 232, 43",99.0,"New York City, New York (United States)",https://i.gr-assets.com/images/S/compressed.ph...,153,3,3.45,"[Mystery, Romance, Crime, Fiction, Futuristic,...",exciting

In [79]:
relaxing_books = moodbooks[moodbooks['mood'] == 'relaxing']
relaxing_books = relaxing_books.drop_duplicates(subset='book-title')
relaxing_books.head()

,isbn_x,book-title,book-author,year-of-publication,publisher_x,image-url-s,image-url-m,image-url-l,bookId,series,...,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price,genre_list,mood
6,0060168013,Pigs in Heaven,Barbara Kingsolver,1993,Harpercollins,http://images.amazon.com/images/P/0060168013.0...,http://images.amazon.com/images/P/0060168013.0...,http://images.amazon.com/images/P/0060168013.0...,14250.Pigs_in_Heaven,Greer Family #2,...,56539,"16557, 24818, 12516, 2024, 624",95.0,,https://i.gr-assets.com/images/S/compressed.ph...,664,8,3.11,"[Fiction, Contemporary, Literary Fiction, Adul...",relaxing
12,042511774X,Breathing Lessons,Anne Tyler,1994,Berkley Publishing Group,http://images.amazon.com/images/P/042511774X.0...,http://images.amazon.com/images/P/042511774X.0...,http://images.amazon.com/images/P/042511774X.0...,31181.Breathing_Lessons,NaN,...,24156,"4704, 9602, 7479, 1805, 566",90.0,,https://i.gr-assets.com/images/S/compressed.ph...,1242,24,4.08,"[Fiction, Contemporary, Literary Fiction, Nove...",relaxing
22,0786868716,The Five People You Meet in Heaven,Mitch Albom,2003,Hyperion,http://images.amazon.com/images/P/0786868716.0...,http://images.amazon.com/images/P/0786868716.0...,http://images.amazon.com/images/P/0786868716.0...,3431.The_Five_People_You_Meet_in_Heaven,The Five People You Meet in Heaven #1,...,578095,"210367, 189807, 125731, 37953, 14237",91.0,United States of America,https://i.gr-assets.com/images/S/compressed.ph...,125048,1441,3.57,"[Fiction, Inspirational, Contemporary, Fantasy...",relaxing
28,0446612545,The Beach House,James Patterson,2003,Warner Books,http://images.amazon.com/images/P/0446612545.0...,http://images.amazon.com/images/P/0446612545.0...,http://images.amazon.com/images/P/0446612545.0...,268406.The_Beach_House,The Beach House #1,...,602,"165, 201, 169, 43, 24",89.0,,https://i.gr-assets.com/images/S/compressed.ph...,69,1,3.28,"[Christian Fiction, Fiction, Chick Lit, Contem...",relaxing
35,0451410319,Hush,Anne Frasier,2002,Onyx Books,http://images.amazon.com/images/P/0451410319.0...,http://images.amazon.com/images/P/0451410319.0...,http://images.amazon.com/images/P/0451410319.0...,34845079-hush,NaN,...,110,"75, 20, 11, 3, 1",96.0,,https://i.gr-assets.com/images/S/compressed.ph...,100,1,NaN,"[Poetry, Romance]",relaxing

In [80]:
thoughtful_books = moodbooks[moodbooks['mood'] == 'thoughtful']
thoughtful_books = thoughtful_books.drop_duplicates(subset='book-title')
thoughtful_books.head()

,isbn_x,book-title,book-author,year-of-publication,publisher_x,image-url-s,image-url-m,image-url-l,bookId,series,...,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price,genre_list,mood
3,0375406328,Lying Awake,Mark Salzman,2000,Alfred A. Knopf,http://images.amazon.com/images/P/0375406328.0...,http://images.amazon.com/images/P/0375406328.0...,http://images.amazon.com/images/P/0375406328.0...,136228.Lying_Awake,NaN,...,2761,"717, 1088, 755, 166, 35",93.0,,https://i.gr-assets.com/images/S/compressed.ph...,78,1,3.79,"[Fiction, Religion, Spirituality, Literature, ...",thoughtful
5,0449005615,Seabiscuit: An American Legend,LAURA HILLENBRAND,2002,Ballantine Books,http://images.amazon.com/images/P/0449005615.0...,http://images.amazon.com/images/P/0449005615.0...,http://images.amazon.com/images/P/0449005615.0...,110737.Seabiscuit,NaN,...,144419,"66572, 50847, 20985, 4168, 1847",96.0,United States of America,https://i.gr-assets.com/images/S/compressed.ph...,12822,190,3.19,"[Nonfiction, History, Biography, Sports, Anima...",thoughtful
14,0140067477,The Tao of Pooh,Benjamin Hoff,1983,Penguin Books,http://images.amazon.com/images/P/0140067477.0...,http://images.amazon.com/images/P/0140067477.0...,http://images.amazon.com/images/P/0140067477.0...,48757.The_Tao_of_Pooh,"The Way, With The Enchanted Neighborhood",...,101520,"38086, 34586, 20957, 5515, 2376",92.0,,https://i.gr-assets.com/images/S/compressed.ph...,1777,29,8.22,"[Philosophy, Nonfiction, Religion, Spiritualit...",thoughtful
15,0451625889,The Prince,Niccolo Machiavelli,1952,Signet Book,http://images.amazon.com/images/P/0451625889.0...,http://images.amazon.com/images/P/0451625889.0...,http://images.amazon.com/images/P/0451625889.0...,28862.The_Prince,NaN,...,259962,"76212, 90803, 68095, 18695, 6157",90.0,,https://i.gr-assets.com/images/S/compressed.ph...,25150,352,5.68,"[Classics, Philosophy, Nonfiction, Politics, H...",thoughtful
20,0316769487,The Catcher in the Rye,J.D. Salinger,1991,"Little, Brown",http://images.amazon.com/images/P/0316769487.0...,http://images.amazon.com/images/P/0316769487.0...,http://images.amazon.com/images/P/0316769487.0...,5107.The_Catcher_in_the_Rye,NaN,...,2736523,"937208, 846027, 579292, 234980, 139016",86.0,"New York City, New York (United States), Agers...",https://i.gr-assets.com/images/S/compressed.ph...,603268,6533,2.6,"[Classics, Fiction, Young Adult, Literature, S...",thoughtful

In [81]:
curious_books = moodbooks[moodbooks['mood'] == 'curious']
curious_books = curious_books.drop_duplicates(subset='book-title')
curious_books.head()

,isbn_x,book-title,book-author,year-of-publication,publisher_x,image-url-s,image-url-m,image-url-l,bookId,series,...,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price,genre_list,mood
224,1842040154,Celtic Myths and Legends,Charles L. Squire,2000,Lomond Books,http://images.amazon.com/images/P/1842040154.0...,http://images.amazon.com/images/P/1842040154.0...,http://images.amazon.com/images/P/1842040154.0...,839793.Celtic_Myths_and_Legends,NaN,...,2633,"914, 844, 703, 122, 50",93.0,,https://i.gr-assets.com/images/S/compressed.ph...,111,2,12.32,"[Mythology, History, Nonfiction, Folklore, Ref...",curious
1836,0451628039,Mythology,Edith Hamilton,1991,Signet Book,http://images.amazon.com/images/P/0451628039.0...,http://images.amazon.com/images/P/0451628039.0...,http://images.amazon.com/images/P/0451628039.0...,23522.Mythology,NaN,...,44903,"15594, 17293, 9346, 1983, 687",94.0,,https://i.gr-assets.com/images/S/compressed.ph...,13479,201,4.32,"[Mythology, Classics, Nonfiction, History, Ref...",curious
2158,0804109192,Sacrifice,Andrew H. Vachss,1992,Ivy Books,http://images.amazon.com/images/P/0804109192.0...,http://images.amazon.com/images/P/0804109192.0...,http://images.amazon.com/images/P/0804109192.0...,10831726-sacrifice,The Descendants #2,...,628,"233, 188, 139, 54, 14",89.0,,https://i.gr-assets.com/images/S/compressed.ph...,86,1,18.95,"[Mythology, Young Adult, Fantasy, Romance, Gre...",curious
4991,0515129496,Resurrection Day,Brendan Dubois,2000,Berkley Publishing Group,http://images.amazon.com/images/P/0515129496.0...,http://images.amazon.com/images/P/0515129496.0...,http://images.amazon.com/images/P/0515129496.0...,184815.Resurrection_Day,NaN,...,1013,"286, 409, 243, 57, 18",93.0,,https://i.gr-assets.com/images/S/compressed.ph...,95,1,5.19,"[Alternate History, Fiction, Science Fiction, ...",curious
5988,0671891537,Betrayal,Gwen Hunter,1994,Pocket Books,http://images.amazon.com/images/P/0671891537.0...,http://images.amazon.com/images/P/0671891537.0...,http://images.amazon.com/images/P/0671891537.0...,10915691-betrayal,The Descendants #1,...,2968,"893, 747, 713, 341, 274",79.0,"Nickel City, Nevada (United States)",https://i.gr-assets.com/images/S/compressed.ph...,132,2,NaN,"[Mythology, Young Adult, Fantasy, Paranormal, ...",curious

In [82]:
happy_books.to_pickle('happy.pkl')
sad_books.to_pickle('sad.pkl')
exciting_books.to_pickle('excited.pkl')
curious_books.to_pickle('curious.pkl')
relaxing_books.to_pickle('relaxed.pkl')
thoughtful_books.to_pickle('thoughtful.pkl')

In [83]:
curious_books.shape

(16, 34)

In [84]:
print(happy_books.columns)

Index(['isbn_x', 'book-title', 'book-author', 'year-of-publication',
       'publisher_x', 'image-url-s', 'image-url-m', 'image-url-l', 'bookId',
       'series', 'author', 'rating', 'description', 'language', 'isbn_y',
       'genres', 'characters', 'bookFormat', 'edition', 'pages', 'publisher_y',
       'publishDate', 'firstPublishDate', 'awards', 'numRatings',
       'ratingsByStars', 'likedPercent', 'setting', 'coverImg', 'bbeScore',
       'bbeVotes', 'price', 'genre_list', 'mood'],
      dtype='object')

In [85]:
relaxing_books.shape

(761, 34)

In [86]:
# Assuming `exciting_books` is a pandas DataFrame
print(relaxing_books[['book-title', 'book-author']].iloc[0:51].to_string(index=False))

                               book-title                book-author
                           Pigs in Heaven         Barbara Kingsolver
                        Breathing Lessons                 Anne Tyler
       The Five People You Meet in Heaven                Mitch Albom
                          The Beach House            James Patterson
                                     Hush               Anne Frasier
                     The Tortilla Curtain       T. Coraghessan Boyle
                         The Journey Home           Isabelle Holland
                                  Waiting          Frank M. Robinson
                                Bel Canto               Ann Patchett
                         The Robber Bride            Margaret Atwood
                     A Widow for One Year                JOHN IRVING
                             Empire Falls              Richard Russo
                           Black and Blue              ANNA QUINDLEN
                           The Bean Trees         Barbara Kingsolver
               Homeland and Other Stories         Barbara Kingsolver
            Vertical Poetry: Recent Poems            Roberto Juarroz
                              Three Junes                JULIA GLASS
                       A Map of the World              Jane Hamilton
                         In This Mountain                  Jan Karon
                         Amy and Isabelle           Elizabeth Strout
                             Saving Grace                  LEE SMITH
                           Charming Billy            Alice McDermott
                          Ordinary People               Judith Guest
                    The Real Mother Goose      Blanche Fisher Wright
                               Fight Club            Chuck Palahniuk
                  Interpreter of Maladies              Jhumpa Lahiri
                              White Teeth                Zadie Smith
          The Perks of Being a Wallflower            Stephen Chbosky
                                    Choke            CHUCK PALAHNIUK
                              Gingerbread                Rachel Cohn
                  A Prayer for Owen Meany                John Irving
                              The Prophet              Kahlil Gibran
                                  Kitchen           Banana Yoshimoto
                                    Speak      Laurie Halse Anderson
                                Surfacing            MARGARET ATWOOD
                             Ellen Foster               Kaye Gibbons
A Heartbreaking Work of Staggering Genius                Dave Eggers
                               Look at Me              Jennifer Egan
                           Walk Two Moons              Sharon Creech
                          Flesh and Blood         Jonathan Kellerman
                                    Mercy              Julie Garwood
                       Sister of My Heart Chitra Banerjee Divakaruni
                           The Acid House               Irvine Welsh
                               After Dark               Jayne Castle
        Dinner at the Homesick Restaurant                 Anne Tyler
                          The Giving Tree           Shel Silverstein
                           How to Be Good                Nick Hornby
                  Veronika Decides to Die               Paulo Coelho
                    The Book of Questions               Pablo Neruda
                           Pay It Forward        Catherine Ryan Hyde
                               Homecoming              Cynthia Voigt

In [89]:
preview_links = pd.read_excel('preview links.xlsx')

In [90]:
preview_links = preview_links.drop_duplicates(subset=['book-title'])

In [91]:
preview_links.shape

(208, 2)

In [92]:
merged_df = bestbooks.merge(preview_links, on='book-title', how='inner')

In [93]:
merged_df = merged_df.drop_duplicates(subset=['book-title'])

In [94]:
merged_df

,bookId,book-title,series,author,rating,description,language,isbn,genres,characters,...,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price,link
0,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"Classics, Fiction, Historical Fiction, School,...","Scout Finch, Atticus Finch, Jem Finch, Arthur ...",...,"Pulitzer Prize for Fiction (1961), Audie Award...",4501075,"2363896, 1333153, 573280, 149952, 80794",95.0,"Maycomb, Alabama (United States)",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,NaN,https://www.google.co.in/books/edition/To_Kill...
1,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,9999999999999,"Classics, Fiction, Romance, Historical Fiction...","Mr. Bennet, Mrs. Bennet, Jane Bennet, Elizabet...",...,,2998241,"1617567, 816659, 373311, 113934, 76770",94.0,"United Kingdom, Derbyshire, England (United Ki...",https://i.gr-assets.com/images/S/compressed.ph...,1983116,20452,NaN,https://books.google.co.in/books?id=kQ0mAAAAMA...
2,170448.Animal_Farm,Animal Farm,NaN,"George Orwell, Russell Baker (Preface), C.M. W...",3.95,Librarians note: There is an Alternate Cover E...,English,9780451526342,"Classics, Fiction, Dystopia, Fantasy, Literatu...","Snowball, Napoleon, Clover, Boxer, Old Major, ...",...,"Prometheus Hall of Fame Award (2011), Retro Hu...",2740713,"986764, 958699, 545475, 165093, 84682",91.0,"England, United Kingdom",https://i.gr-assets.com/images/S/compressed.ph...,1276599,13264,4.42,https://www.google.co.in/books/edition/Animal_...
3,6185.Wuthering_Heights,Wuthering Heights,NaN,"Emily Brontë, Richard J. Dunn (Editor), David ...",3.86,You can find the redesigned cover of this edit...,English,9780393978896,"Classics, Fiction, Romance, Gothic, Literature...","Heathcliff, Catherine Earnshaw, Edgar Linton, ...",...,,1342664,"483222, 413051, 279702, 107437, 59252",88.0,"Yorkshire Dales, England",https://i.gr-assets.com/images/S/compressed.ph...,981502,10275,2.73,https://www.google.co.in/books/edition/Wutheri...
4,968.The_Da_Vinci_Code,The Da Vinci Code,Robert Langdon #2,Dan Brown (Goodreads Author),3.86,ISBN 9780307277671 moved to this edition.While...,English,9999999999999,"Fiction, Mystery, Thriller, Suspense, Mystery ...","Sophie Neveu, Robert Langdon, Sir Leigh Teabin...",...,British Book Award for Book of the Year (2005)...,1933446,"645308, 667657, 399278, 142103, 79100",89.0,"Paris (France), London, England, France, Engla...",https://i.gr-assets.com/images/S/compressed.ph...,876633,9231,NaN,https://www.google.co.in/books/edition/The_Da_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,944291.Wednesday_the_Rabbi_Got_Wet,Wednesday the Rabbi Got Wet,The Rabbi Small Mysteries #6,Harry Kemelman,3.89,The sixth in the ibooks series of definitive e...,English,9780688030605,"Mystery, Fiction, Jewish, Judaism, Religion, C...",,...,,1042,"260, 440, 312, 24, 6",97.0,,https://i.gr-assets.com/images/S/compressed.ph...,44,1,5.36,https://www.google.co.in/books/edition/Wednesd...
212,29617.White_Lies,White Lies,The Arcane Society #2,Jayne Ann Krentz (Goodreads Author),4.02,Relationships are challenging enough for most ...,English,9780399153730,"Romance, Paranormal Romance, Paranormal, Myste...","Clare Lancaster, Jake Salter",...,,9026,"3033, 3595, 2039, 294, 65",96.0,"Stone Canyon, Arizona (United States)",https://i.gr-assets.com/images/S/compressed.ph...,38,1,3.13,https://www.google.co.in/books/edition/White_L...
213,13066.Sick_Puppy,Sick Puppy,Skink #4,Carl Hiaasen (Goodreads Author),3.90,Independently wealthy eco-terrorist Twilly Spr...,English,9780446695688,"Fiction, Humor, Mystery, Crime, Comedy, Thrill...","Twilly Spree, Palmer Stoat, Desirata Stoat, Go...",...,,22524,"5952, 9686, 5714, 949, 223",95.0,Florida (United States),https://i.gr-assets.com/images/S/compressed.ph...,36,1,3.28,https://books.google.co.in/books?id=3L2KEAAAQB...
214,379095.The_Morning_After,The Morning After,Savannah #2,Lisa Jackson (Goodreads Author),4.09,"Determined to make a name for herself, Savanna...",English,9780821772959,"Mystery, Romantic Suspense, Thriller, Suspense...",,...,,5445,"2073, 2032, 1132, 167, 41",96.0,,https://i.gr-assets.com/images/S/compressed.ph...,20,1,3.49,https://www.google.co.in/books/edition/The_Mor...
216,9589.Hocus_Pocus,Hocus Pocus,NaN,Kurt Vonnegut Jr.,3.83,Here is the adventure of Eugene Debs Hartke. H...,English,9780425161296,"Fiction, Humor, Science Fiction, Classics, Lit...",,...,,29958,"6987, 12691, 8566, 1480, 234",94.0,New York State (United States),https://i.gr-assets.com/images/S/compressed.ph...,12,1,14.00,https://www.google.co.in/books/edition/Hocus_P...

In [95]:
print(merged_df.columns)

Index(['bookId', 'book-title', 'series', 'author', 'rating', 'description',
       'language', 'isbn', 'genres', 'characters', 'bookFormat', 'edition',
       'pages', 'publisher', 'publishDate', 'firstPublishDate', 'awards',
       'numRatings', 'ratingsByStars', 'likedPercent', 'setting', 'coverImg',
       'bbeScore', 'bbeVotes', 'price', 'link'],
      dtype='object')

In [96]:
merged_df.shape

(156, 26)

In [97]:
merged_df.to_pickle('preview.pkl')

In [98]:
print(books.columns)

Index(['isbn', 'book-title', 'book-author', 'year-of-publication', 'publisher',
       'image-url-s', 'image-url-m', 'image-url-l'],
      dtype='object')

In [99]:
print(ratings.columns)

Index(['user-id', 'isbn', 'book-rating'], dtype='object')

In [100]:
print("Users in pt:", pt.index)

Users in pt: Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='book-title', length=706)

In [101]:
print(bestbooks.columns)

Index(['bookId', 'book-title', 'series', 'author', 'rating', 'description',
       'language', 'isbn', 'genres', 'characters', 'bookFormat', 'edition',
       'pages', 'publisher', 'publishDate', 'firstPublishDate', 'awards',
       'numRatings', 'ratingsByStars', 'likedPercent', 'setting', 'coverImg',
       'bbeScore', 'bbeVotes', 'price'],
      dtype='object')

In [102]:
print(relaxing_books)

           isbn_x                          book-title         book-author  \
6      0060168013                      Pigs in Heaven  Barbara Kingsolver
12     042511774X                   Breathing Lessons          Anne Tyler
22     0786868716  The Five People You Meet in Heaven         Mitch Albom
28     0446612545                     The Beach House     James Patterson
35     0451410319                                Hush        Anne Frasier
...           ...                                 ...                 ...
26051  0440340268                 In Watermelon Sugar   Richard Brautigan
26102  0932379028                        Mohawk Trail          Beth Brant
26151  0751525243                              Purity        Shaun Hutson
26159  0373272510                   The Cop Next Door         Jenna Mills
26175  0743509978                         Good Harbor       Anita Diamant

      year-of-publication                 publisher_x  \
6                    1993               Harpercollins
12                   1994    Berkley Publishing Group
22                   2003                    Hyperion
28                   2003                Warner Books
35                   2002                  Onyx Books
...                   ...                         ...
26051                1985           Bantam Books (Mm)
26102                1985             Firebrand Books
26151                1999          Acacia Press, Inc.
26159                2002                  Silhouette
26175                2001  Simon &amp; Schuster Audio

                                             image-url-s  \
6      http://images.amazon.com/images/P/0060168013.0...
12     http://images.amazon.com/images/P/042511774X.0...
22     http://images.amazon.com/images/P/0786868716.0...
28     http://images.amazon.com/images/P/0446612545.0...
35     http://images.amazon.com/images/P/0451410319.0...
...                                                  ...
26051  http://images.amazon.com/images/P/0440340268.0...
26102  http://images.amazon.com/images/P/0932379028.0...
26151  http://images.amazon.com/images/P/0751525243.0...
26159  http://images.amazon.com/images/P/0373272510.0...
26175  http://images.amazon.com/images/P/0743509978.0...

                                             image-url-m  \
6      http://images.amazon.com/images/P/0060168013.0...
12     http://images.amazon.com/images/P/042511774X.0...
22     http://images.amazon.com/images/P/0786868716.0...
28     http://images.amazon.com/images/P/0446612545.0...
35     http://images.amazon.com/images/P/0451410319.0...
...                                                  ...
26051  http://images.amazon.com/images/P/0440340268.0...
26102  http://images.amazon.com/images/P/0932379028.0...
26151  http://images.amazon.com/images/P/0751525243.0...
26159  http://images.amazon.com/images/P/0373272510.0...
26175  http://images.amazon.com/images/P/0743509978.0...

                                             image-url-l  \
6      http://images.amazon.com/images/P/0060168013.0...
12     http://images.amazon.com/images/P/042511774X.0...
22     http://images.amazon.com/images/P/0786868716.0...
28     http://images.amazon.com/images/P/0446612545.0...
35     http://images.amazon.com/images/P/0451410319.0...
...                                                  ...
26051  http://images.amazon.com/images/P/0440340268.0...
26102  http://images.amazon.com/images/P/0932379028.0...
26151  http://images.amazon.com/images/P/0751525243.0...
26159  http://images.amazon.com/images/P/0373272510.0...
26175  http://images.amazon.com/images/P/0743509978.0...

                                        bookId  \
6                         14250.Pigs_in_Heaven
12                     31181.Breathing_Lessons
22     3431.The_Five_People_You_Meet_in_Heaven
28                      268406.The_Beach_House
35                               34845079-hush
...                                        ...
26051                46182.In_Watermelon_Sugar
26102                     2965062-mohawk-trail
26151                          23754479-purity
26159               12610592-the-cop-next-door
26175                        25717.Good_Harbor

                                      series  ... numRatings  \
6                            Greer Family #2  ...      56539
12                                       NaN  ...      24156
22     The Five People You Meet in Heaven #1  ...     578095
28                        The Beach House #1  ...        602
35                                       NaN  ...        110
...                                      ...  ...        ...
26051                                    NaN  ...      13211
26102                                    NaN  ...         28
26151                                    NaN  ...      41578
26159                           F.U.C Series  ...        167
26175                                    NaN  ...       7271

                             ratingsByStars likedPercent  \
6            16557, 24818, 12516, 2024, 624         95.0
12              4704, 9602, 7479, 1805, 566         90.0
22     210367, 189807, 125731, 37953, 14237         91.0
28                    165, 201, 169, 43, 24         89.0
35                         75, 20, 11, 3, 1         96.0
...                                     ...          ...
26051            4982, 4526, 2589, 789, 325         92.0
26102                         9, 8, 9, 2, 0         93.0
26151        8136, 16218, 11839, 3914, 1471         87.0
26159                    37, 36, 55, 27, 12         77.0
26175            653, 2121, 3204, 1071, 222         82.0

                                   setting  \
6
12
22                United States of America
28
35
...                                    ...
26051  Bolinas, California (United States)
26102
26151                     Berlin (Germany)
26159
26175

                                                coverImg bbeScore bbeVotes  \
6      https://i.gr-assets.com/images/S/compressed.ph...      664        8
12     https://i.gr-assets.com/images/S/compressed.ph...     1242       24
22     https://i.gr-assets.com/images/S/compressed.ph...   125048     1441
28     https://i.gr-assets.com/images/S/compressed.ph...       69        1
35     https://i.gr-assets.com/images/S/compressed.ph...      100        1
...                                                  ...      ...      ...
26051  https://i.gr-assets.com/images/S/compressed.ph...      469        5
26102  https://i.gr-assets.com/images/S/compressed.ph...       66        1
26151  https://i.gr-assets.com/images/S/compressed.ph...       66        1
26159  https://i.gr-assets.com/images/S/compressed.ph...       75        1
26175  https://i.gr-assets.com/images/S/compressed.ph...       97        1

      price                                         genre_list      mood
6      3.11  [Fiction, Contemporary, Literary Fiction, Adul...  relaxing
12     4.08  [Fiction, Contemporary, Literary Fiction, Nove...  relaxing
22     3.57  [Fiction, Inspirational, Contemporary, Fantasy...  relaxing
28     3.28  [Christian Fiction, Fiction, Chick Lit, Contem...  relaxing
35      NaN                                  [Poetry, Romance]  relaxing
...     ...                                                ...       ...
26051  6.10  [Fiction, Poetry, Fantasy, American, Novels, L...  relaxing
26102  5.20  [Poetry, LGBT, Short Stories, Fiction, Canada,...  relaxing
26151  4.22  [Fiction, Contemporary, Novels, Literary Ficti...  relaxing
26159   NaN  [Erotica, Short Stories, Contemporary, BDSM, E...  relaxing
26175  1.85  [Fiction, Contemporary, Chick Lit, Novels, Wom...  relaxing

[761 rows x 34 columns]